// <auto-generated />
namespace MovieStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SetNotNullForUserInMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetNotNullForUserInMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201902091044424_SetNotNullForUserInMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
